version: "3.9"

services:

    portfawn:
        build: .

    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: portfawn_user
            MONGO_INITDB_ROOT_PASSWORD: portfawn_pass